package com.balancee.test.models;

import jakarta.persistence.*;
//lombrok to generate getters, setters, constructors, and other boilerplate code, to reduce code clutter.
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;


@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "user_table")
public class User {

    @Id
    @SequenceGenerator(
            name = "user_sequence",
            sequenceName = "user_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "user_sequence"
    )
    private Long userId;  // Unique identifier for the user

    @Column(name = "user_name", nullable = false, unique = true)
    private String username;  // Username of the user

    @Column(name = "password", nullable = false)
    private String password; // Password of the user

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Date createdAt; // Timestamp for user creation

    private String roles = "ROLE_USER"; // Default user role


    @UpdateTimestamp
    @Column(name = "update_at")
    private Date updatedAt;  // Timestamp for user update

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // Getters and setters are generated by Lombok
}
